// ============================================================================
// LCD_Hw.c - Hardware Abstraction Layer for Nios II on DE10-Standard
// ============================================================================

#include "LCD_Hw.h"
#include "system.h"                    // Generated by Qsys - contains base addresses
#include "altera_avalon_spi.h"         // Nios II SPI driver
#include "altera_avalon_pio_regs.h"    // Nios II PIO driver
#include <unistd.h>                    // For usleep()

// ============================================================================
// Pin Definitions (directly in Qsys names)
// Make sure these match your Qsys component names!
// ============================================================================

// If your Qsys names differ, change these:
// SPI_LCD_BASE      - SPI master base address (from system.h)
// LCD_A0_BASE       - PIO for A0/RS pin (from system.h)  
// LCD_RST_BASE      - PIO for Reset pin (from system.h)

// A0 (RS) Pin States
#define LCD_A0_COMMAND  0    // A0 = 0 for command
#define LCD_A0_DATA     1    // A0 = 1 for data

// Reset Pin States
#define LCD_RST_ACTIVE   0   // Active low reset
#define LCD_RST_INACTIVE 1

// SPI slave select (typically 0 for single device)
#define LCD_SPI_SLAVE   0

// ============================================================================
// Delay Functions
// ============================================================================

void LCDHW_DelayUs(uint32_t us) {
    usleep(us);
}

void LCDHW_DelayMs(uint32_t ms) {
    usleep(ms * 1000);
}

// ============================================================================
// Hardware Reset
// ============================================================================

void LCDHW_Reset(void) {
    // Assert reset (active low)
    IOWR_ALTERA_AVALON_PIO_DATA(LCD_RST_BASE, LCD_RST_ACTIVE);
    LCDHW_DelayMs(10);
    
    // Release reset
    IOWR_ALTERA_AVALON_PIO_DATA(LCD_RST_BASE, LCD_RST_INACTIVE);
    LCDHW_DelayMs(50);  // Wait for LCD to stabilize
}

// ============================================================================
// Initialize Hardware
// ============================================================================

void LCDHW_Init(void) {
    // Set initial pin states
    IOWR_ALTERA_AVALON_PIO_DATA(LCD_A0_BASE, LCD_A0_COMMAND);
    IOWR_ALTERA_AVALON_PIO_DATA(LCD_RST_BASE, LCD_RST_INACTIVE);
    
    // Perform hardware reset
    LCDHW_Reset();
}

// ============================================================================
// Write 8-bit Value to LCD via SPI
// ============================================================================

void LCDHW_Write8(int is_data, uint8_t value) {
    // Step 1: Set A0 pin (0 = command, 1 = data)
    if (is_data) {
        IOWR_ALTERA_AVALON_PIO_DATA(LCD_A0_BASE, LCD_A0_DATA);
    } else {
        IOWR_ALTERA_AVALON_PIO_DATA(LCD_A0_BASE, LCD_A0_COMMAND);
    }
    
    // Small delay to ensure A0 is stable before SPI clock
    LCDHW_DelayUs(1);
    
    // Step 2: Send byte via SPI
    alt_avalon_spi_command(
        SPI_LCD_BASE,       // SPI master base address
        LCD_SPI_SLAVE,      // Slave select (0)
        1,                  // Write length (1 byte)
        &value,             // Data to write
        0,                  // Read length (0 - no read)
        NULL,               // Read buffer (NULL - not reading)
        0                   // Flags
    );
}